name: Create manifest

on:
  workflow_dispatch:

jobs:
  manifest:
    runs-on: ubuntu-latest
    steps:
      - run: docker pull alpine:latest
      - name: Manifest Generation
        run: |
          export BILLY_SERVER=https://billy.dev-aqua.codesec.aquasec.com
          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
          if ! cat install.sh.checksum | sha256sum --check; then
          echo "install.sh checksum failed"
          exit 1
          fi
          BINDIR="." sh install.sh
          rm install.sh install.sh.checksum
          ./billy generate \
            --access-token "${{ secrets.GITHUB_TOKEN }}" \
            --aqua-key "" \
            --aqua-secret "" \
            --cspm-url https://stage.api.cloudsploit.com \
            --artifact-path docker pull alpine:latest
